### PR TITLE
Merge DGS into Master

### PR DESCRIPTION
**Pull request by lburak**
Changed so that we now prioritize extra ticket choice over forcing couples together.

### CODE REVIEW

**Comment by atin121** [comment]
Looks like open paren on line 55 after random.seed - runs great otherwise! super fun solution

**Review by sjavdani — APPROVED** [review]
LGTM! :ship: it

**Review by beneckart — COMMENTED** [review]
Cool! I wasn't part of the call and am a bit behind on slack, but this algorithm seems to be: 1) randomly allocate who gets our extras from those that want an extra, 2) pair up remaining people, with a preference for couple matching

Is step 2 preferential to couple matching because it makes finances easier? Without couple matching, you could do this in much fewer lines :)

    ppl2 = sorted(list(set(people) - set(people_who_want_one)), key=lambda k: random.random())
    ppl1 = ppl2[num_tickets-len(people):] + people_who_want_one
    print 'people who get two:', ppl2[:num_tickets-len(people)]
    print 'remaining pairs:', [(ppl1[i], ppl1[i+1]) for i in range(0,len(ppl1),2)]

**Comment by lburak** [comment]
Yes. That is correct it pairs up the remaining people with a preference for matching couples. And yes, changing the requirements to be simpler results in less code ;)

Also I wrote the code to be as purposely verbose as I could given that there were non-programmers who had a stake in understanding what the code was doing, and list comprehensions are not particularly friendly concepts if you've never seen them before.

**Pull request merged**
